services:  
  # Single PostgreSQL instance for all services
  db:
    image: postgres
    restart: always
    container_name: postgresql_shared
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: shared_db
    ports:
      - "5432:5432"
    networks:
      app_net:
        ipv4_address: 192.168.0.2

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - ./data/pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      app_net:
        ipv4_address: 192.168.0.3

  placement_officers:
    build:
      context: .
      dockerfile: placement_officers/Dockerfile
    container_name: placement_officers
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "placement_officers.wsgi:application"]
    volumes:
      - ./placement_officers:/app
    ports:
      - "8001:8000"
    depends_on:
      - db
    networks:
      app_net:
        ipv4_address: 192.168.0.5
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@db:5432/shared_db

  placement_team:
    build:
      context: .
      dockerfile: placement_team/Dockerfile
    container_name: placement_team
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "placement_team.wsgi:application"]
    volumes:
      - ./placement_team:/app
    ports:
      - "8002:8000"
    depends_on:
      - db
    networks:
      app_net:
        ipv4_address: 192.168.0.6
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@db:5432/shared_db

  program_managers:
    build:
      context: . 
      dockerfile: program_managers/Dockerfile
    container_name: program_managers
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "program_managers.wsgi:application"]
    volumes:
      - ./program_managers:/app
    ports:
      - "8003:8000"
    depends_on:
      - db
    networks:
      app_net:
        ipv4_address: 192.168.0.7
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@db:5432/shared_db

  recruiters:
    build:
      context: . 
      dockerfile: recruiters/Dockerfile
    container_name: recruiters
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "recruiters.wsgi:application"]
    volumes:
      - ./recruiters:/app
    ports:
      - "8004:8000"
    depends_on:
      - db
    networks:
      app_net:
        ipv4_address: 192.168.0.8
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@db:5432/shared_db

  students:
    build:
      context: . 
      dockerfile: students/Dockerfile
    container_name: students
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "students.wsgi:application"]
    volumes:
      - ./students:/app
    ports:
      - "8005:8000"
    depends_on:
      - db
    networks:
      app_net:
        ipv4_address: 192.168.0.9
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@db:5432/shared_db

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.0.0/24"
          gateway: 192.168.0.1
