FROM python:3.9

WORKDIR /app

COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/

EXPOSE 8000

#Run the Django gunicorn serven in production
CMD ["gunicorn","bind","0.0.0.0:8000","placement_officers.wsgi:application"]
