# Generated by Django 5.1.6 on 2025-03-03 14:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job_fairs',
            fields=[
                ('job_fair_id', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=100)),
                ('date_of_job_fair', models.DateField()),
                ('date_of_creation', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
