# Generated by Django 5.1.6 on 2025-03-03 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement_team_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='job_fairs',
            table='job_fairs',
        ),
    ]
