# Generated by Django 5.1.6 on 2025-03-04 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_team_app', '0002_alter_job_fairs_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_fairs',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
