# Generated by Django 5.1.6 on 2025-03-05 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_team_app', '0003_job_fairs_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('recruiter_id', models.AutoField(primary_key=True, serialize=False)),
                ('recruiter_email', models.EmailField(max_length=255, unique=True)),
                ('recruiter_password', models.CharField(max_length=255)),
                ('recruiter_qr_code', models.ImageField(blank=True, null=True, upload_to='recruiter_qr_codes/')),
            ],
            options={
                'db_table': 'recruiter',
            },
        ),
        migrations.CreateModel(
            name='RecruiterJobFair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_fair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement_team_app.job_fairs')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement_team_app.recruiter')),
            ],
            options={
                'db_table': 'recruiter_job_fair',
                'unique_together': {('recruiter', 'job_fair')},
            },
        ),
    ]
