# Generated by Django 5.1.6 on 2025-03-05 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_team_app', '0004_recruiter_recruiterjobfair'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recruiterjobfair',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='recruiterjobfair',
            name='job_fair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_fair_recruiters', to='placement_team_app.job_fairs'),
        ),
        migrations.AlterField(
            model_name='recruiterjobfair',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_job_fairs', to='placement_team_app.recruiter'),
        ),
        migrations.AddConstraint(
            model_name='recruiterjobfair',
            constraint=models.UniqueConstraint(fields=('recruiter', 'job_fair'), name='unique_recruiter_job_fair'),
        ),
    ]
